name: Build Backend

on:
  workflow_run:
    workflows: ["Build Frontend"]
    types:
      - completed

env:
  BACK_DIR: ./backend
  BACK_IMAGE_NAME: backendapp

jobs:
  build-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build backend (Maven)
        run: |
          cd ${{ env.BACK_DIR }}
          mvn clean package -DskipTests
