name: Backend CI/CD

on:
  push:
    paths:
      - 'backend/**'
      - '.github/workflows/backend.yml'
  workflow_dispatch:

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Build with Maven
        run: mvn -B -f backend/pom.xml clean package
      - name: Docker Build & Push
        run: |
      - name: Azure Web App Deploy
        uses: azure/webapps-deploy@v3
        with:
      - name: Azure Web App Deploy
        uses: azure/webapps-deploy@v3
        with:
          docker build -t ${{ secrets.DOCKER_USER }}/yazeed-burger-backend:latest ./backend
          echo ${{ secrets.DOCKER_PASS }} | docker login -u ${{ secrets.DOCKER_USER }} --password-stdin
          docker push ${{ secrets.DOCKER_USER }}/yazeed-burger-backend:latest
      - name: Azure Web App Deploy
        uses: azure/webapps-deploy@v3
        with:
          app-name: yazeed-be-app-yazeed
          images: ${{ secrets.DOCKER_USER }}/yazeed-burger-backend:latest
