name: Build & Push Backend Docker Image

on:
  push:
    paths:
      - 'backend/**'
    branches: [ main ]
  workflow_dispatch:

env:
  BACK_DIR: ./backend
  BACK_IMAGE_NAME: backendapp

jobs:
  build-and-push-backend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build backend (Maven)
        run: |
          cd ${{ env.BACK_DIR }}
          mvn clean package -DskipTests

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & Push Backend Image
        uses: docker/build-push-action@v4
        with:
          context: ${{ env.BACK_DIR }}
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.BACK_IMAGE_NAME }}:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.BACK_IMAGE_NAME }}:${{ github.sha }}
