name: Full CI/CD Pipeline

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  TF_AUTHOR: "ibrahim-221"
  TF_RESOURCE_PREFIX: "ibra-53"
  TF_RG_NAME: "ibra-new22"
  TF_RG_LOCATION: "canadacentral"
  TF_CONTACT_NAME: "Ibrahim"
  TF_CONTACT_EMAIL: "ibrahim@example.com"
  TF_FE_PORT: 80
  TF_BE_PORT: 8080

  FRONT_DIR: ./frontend
  BACK_DIR: ./backend

  FRONT_IMAGE_NAME: frontendapp
  BACK_IMAGE_NAME: backendapp

jobs:
  build-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
          cache: npm
          cache-dependency-path: ${{ env.FRONT_DIR }}/package-lock.json

      - name: Install frontend dependencies
        run: |
          cd ${{ env.FRONT_DIR }}
          npm ci

      - name: Build frontend
        run: |
          cd ${{ env.FRONT_DIR }}
          npm run build 2>/dev/null || echo "No build step"

  build-backend:
    runs-on: ubuntu-latest
    needs: build-frontend
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build backend (Maven)
        run: |
          cd ${{ env.BACK_DIR }}
          mvn clean package -DskipTests

  docker-and-terraform:
    runs-on: ubuntu-latest
    needs: build-backend
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set image tag
        run: echo "TAG=${GITHUB_SHA}" >> $GITHUB_ENV

      - name: Build & Push frontend image
        uses: docker/build-push-action@v4
        with:
          context: ${{ env.FRONT_DIR }}
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.FRONT_IMAGE_NAME }}:${{ github.sha }}
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.FRONT_IMAGE_NAME }}:latest

      - name: Build & Push backend image
        uses: docker/build-push-action@v4
        with:
          context: ${{ env.BACK_DIR }}
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.BACK_IMAGE_NAME }}:${{ github.sha }}
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.BACK_IMAGE_NAME }}:latest

      - name: Azure Login
        uses: azure/login@v2
        with:
          auth-type: 'service-principal'
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          client-secret: ${{ secrets.AZURE_CLIENT_SECRET }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      - name: Terraform Init
        working-directory: ./terraform
        run: terraform init -input=false

      - name: Terraform Plan
        working-directory: ./terraform
        run: |
          terraform plan -input=false -out=tfplan \
            -var "author=${{ env.TF_AUTHOR }}" \
            -var "resource_prefix=${{ env.TF_RESOURCE_PREFIX }}" \
            -var "resource_group_name=${{ env.TF_RG_NAME }}" \
            -var "resource_group_location=${{ env.TF_RG_LOCATION }}" \
            -var "contact_person_name=${{ env.TF_CONTACT_NAME }}" \
            -var "contact_person_email=${{ env.TF_CONTACT_EMAIL }}" \
            -var "fe_port=${{ env.TF_FE_PORT }}" \
            -var "be_port=${{ env.TF_BE_PORT }}" \
            -var "db_password=${{ secrets.TF_DB_PASSWORD }}" \
            -var "fe_image_name_and_tag=${{ secrets.DOCKERHUB_USERNAME }}/frontendapp:${{ github.sha }}" \
            -var "be_image_name_and_tag=${{ secrets.DOCKERHUB_USERNAME }}/backendapp:${{ github.sha }}"

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main'
        working-directory: ./terraform
        run: terraform apply -input=false -auto-approve tfplan
