name: Build Frontend

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  FRONT_DIR: ./frontend
  FRONT_IMAGE_NAME: frontendapp

jobs:
  build-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
          cache: npm
          cache-dependency-path: ${{ env.FRONT_DIR }}/package-lock.json

      - name: Install frontend dependencies
        run: |
          cd ${{ env.FRONT_DIR }}
          npm ci

      - name: Build frontend
        run: |
          cd ${{ env.FRONT_DIR }}
          npm run build 2>/dev/null || echo "No build step"
