name: Build & Push Frontend Docker Image

on:
  push:
    paths:
      - 'frontend/**'
    branches: [ main ]
  workflow_dispatch:

env:
  FRONT_DIR: ./frontend
  FRONT_IMAGE_NAME: frontendapp

jobs:
  build-and-push-frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
          cache: npm
          cache-dependency-path: ${{ env.FRONT_DIR }}/package-lock.json

      - name: Install dependencies
        run: |
          cd ${{ env.FRONT_DIR }}
          npm ci

      - name: Build frontend
        run: |
          cd ${{ env.FRONT_DIR }}
          npm run build 2>/dev/null || echo "No build step"

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & Push Frontend Image
        uses: docker/build-push-action@v4
        with:
          context: ${{ env.FRONT_DIR }}
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.FRONT_IMAGE_NAME }}:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.FRONT_IMAGE_NAME }}:${{ github.sha }}
